using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using SQLSolutions.Models;

namespace SQLSolutions.Areas.Admin.ViewModels
{
    public class BookIndex
    {
        public IEnumerable<Book> Books { get; set; }
    }

    public class BookNew
    {
        //is assetnum is autogenerated
        [Required]
        public int AssetNum { get; set; }
        [Required]
        public string Isbn { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public string CourseSection { get; set; }
        [Required]
        public int Year { get; set; }
        [Required]
        public int Edition { get; set; }
        [Required]
        public bool IsRequired { get; set; }
    }

    public class BookEdit
    {
        [Required]
        public int AssetNum { get; set; }
        [Required]
        public string Isbn { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public string CourseSection { get; set; }
        [Required]
        public int Year { get; set; }
        [Required]
        public int Edition { get; set; }
        [Required]
        public bool IsRequired { get; set; }
    }
}